In [140]:
import pandas as pd 
import seaborn as sns

In [141]:
df=pd.read_csv(r'C:\Users\YUSEF\Downloads\Compressed\Airbnb_Open_Data.csv\Airbnb_Open_Data.csv')
df

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\1092840129.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r'C:\Users\YUSEF\Downloads\Compressed\Airbnb_Open_Data.csv\Airbnb_Open_Data.csv')

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [142]:
df.license.value_counts()
#! drop this shit

license
41662/AL    2
Name: count, dtype: int64

In [143]:
df.drop(columns='license',inplace=True)

In [144]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and..."
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN

In [145]:
df.host_identity_verified.unique()

array(['unconfirmed', 'verified', nan], dtype=object)

In [146]:
df.host_identity_verified.isna().value_counts()
#! 289

host_identity_verified
False    102310
True        289
Name: count, dtype: int64

In [147]:
df.host_identity_verified.isna()

0         False
1         False
2          True
3         False
4         False
          ...
102594    False
102595    False
102596    False
102597    False
102598    False
Name: host_identity_verified, Length: 102599, dtype: bool

In [148]:
df.host_identity_verified

0         unconfirmed
1            verified
2                 NaN
3         unconfirmed
4            verified
             ...
102594       verified
102595    unconfirmed
102596    unconfirmed
102597    unconfirmed
102598    unconfirmed
Name: host_identity_verified, Length: 102599, dtype: object

In [149]:
df.host_identity_verified.value_counts()

host_identity_verified
unconfirmed    51200
verified       51110
Name: count, dtype: int64

In [150]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and..."
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN

In [151]:
dfc = df.dropna(subset=['NAME','host_identity_verified','host name','neighbourhood group','neighbourhood','lat','long','country','country code','price','Construction year','room type','cancellation_policy','instant_bookable','service fee','availability 365','calculated host listings count','review rate number','reviews per month','number of reviews','minimum nights'])

In [152]:
dfc.dropna(subset='last review',inplace=True)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\2139616325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc.dropna(subset='last review',inplace=True)

In [153]:
dfc

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$577,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs."
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,"$1,060",$212,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102588,6089124,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,...,$618,$124,1.0,177.0,6/29/2019,3.78,4.0,1.0,410.0,Keep the apartment clean and damage free please.
102591,6090781,Columbus Ave Apt 1 block from Park,50908010324,verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,United States,...,"$1,139",$228,5.0,17.0,1/4/2019,0.35,5.0,1.0,134.0,#NAME?
102593,6091885,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,...,"$1,099",$220,1.0,8.0,9/6/2015,0.16,4.0,2.0,152.0,* No smoking indoors. * No pets * No loud/la...
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN

In [154]:
columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
'country code', 'instant_bookable', 'cancellation_policy', 'room type',
'Construction year', 'price', 'service fee', 'minimum nights',
'number of reviews', 'last review']
columns_to_drop = ['reviews per month',
'review rate number', 'calculated host listings count',
'availability 365', 'house_rules', 'License', 'id']

In [155]:
dfc = dfc[columns_to_keep]
dfc

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102588,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,US,True,flexible,Entire home/apt,2016.0,$618,$124,1.0,177.0,6/29/2019
102591,Columbus Ave Apt 1 block from Park,50908010324,verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,United States,US,False,strict,Entire home/apt,2005.0,"$1,139",$228,5.0,17.0,1/4/2019
102593,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,US,True,strict,Private room,2017.0,"$1,099",$220,1.0,8.0,9/6/2015
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015

In [156]:
dfc['neighbourhood group'].unique()

array(['Brooklyn', 'Manhattan', 'brookln', 'Queens', 'Bronx',
       'Staten Island'], dtype=object)

In [157]:
# Extract meanings of cancellation policy, room type, service fee, and review differences
# Define a dictionary for cancellation policy meanings
cancellation_policy_meanings = {
    "strict": "No refund if canceled late",
    "moderate": "Partial refund if canceled",
    "flexible": "Full refund if canceled early"
}
# Define a dictionary for room type meanings
room_type_meanings = {
    "Private room": "A private room in a shared space",
    "Entire home/apt": "The entire property is rented",
    "Shared room": "A shared room in a shared space"
}
# Define the meaning of service fee
service_fee_meaning = "A fee charged for services provided"
# Calculate the difference between all reviews
dfc['Answer'] = dfc['number of reviews'].max() - dfc['number of reviews'].min()
# Combine all meanings and differences into a DataFrame

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\765932898.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc['Answer'] = dfc['number of reviews'].max() - dfc['number of reviews'].min()

In [163]:
dfc.price = dfc.price.str.replace(',',repl='').str.replace('$','').astype(int)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\2143119411.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc.price = dfc.price.str.replace(',',repl='').str.replace('$','').astype(int)

In [165]:
dfc['service fee'] = dfc['service fee'].str.replace(',',repl='').str.replace('$','').astype(int)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\404591309.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc['service fee'] = dfc['service fee'].str.replace(',',repl='').str.replace('$','').astype(int)

In [166]:
dfc

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,Answer
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,966,193,10.0,9.0,10/19/2021,1023.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,142,28,30.0,45.0,5/21/2022,1023.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,204,41,10.0,9.0,11/19/2018,1023.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,577,115,3.0,74.0,6/22/2019,1023.0
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,1060,212,45.0,49.0,10/5/2017,1023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102588,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,US,True,flexible,Entire home/apt,2016.0,618,124,1.0,177.0,6/29/2019,1023.0
102591,Columbus Ave Apt 1 block from Park,50908010324,verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,United States,US,False,strict,Entire home/apt,2005.0,1139,228,5.0,17.0,1/4/2019,1023.0
102593,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,US,True,strict,Private room,2017.0,1099,220,1.0,8.0,9/6/2015,1023.0
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,837,167,1.0,1.0,7/6/2015,1023.0
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,546,109,2.0,5.0,10/11/2015,1023.0

In [175]:
dfc.drop(index= dfc[dfc['minimum nights'] < 0 ].index, inplace=True)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\1329387656.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc.drop(index= dfc[dfc['minimum nights'] < 0 ].index, inplace=True)

In [176]:
dfc[dfc['minimum nights'] < 0 ]

Empty DataFrame
Columns: [NAME, host id, host_identity_verified, host name, neighbourhood group, neighbourhood, lat, long, country, country code, instant_bookable, cancellation_policy, room type, Construction year, price, service fee, minimum nights, number of reviews, last review, Answer]
Index: []

In [177]:
dfc

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,Answer
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,966,193,10.0,9.0,10/19/2021,1023.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,142,28,30.0,45.0,5/21/2022,1023.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,204,41,10.0,9.0,11/19/2018,1023.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,577,115,3.0,74.0,6/22/2019,1023.0
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,1060,212,45.0,49.0,10/5/2017,1023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102588,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,US,True,flexible,Entire home/apt,2016.0,618,124,1.0,177.0,6/29/2019,1023.0
102591,Columbus Ave Apt 1 block from Park,50908010324,verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,United States,US,False,strict,Entire home/apt,2005.0,1139,228,5.0,17.0,1/4/2019,1023.0
102593,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,US,True,strict,Private room,2017.0,1099,220,1.0,8.0,9/6/2015,1023.0
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,837,167,1.0,1.0,7/6/2015,1023.0
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,546,109,2.0,5.0,10/11/2015,1023.0

In [180]:
# ! convert to int
dfc[['Construction year','minimum nights','number of reviews']] = dfc[['Construction year','minimum nights','number of reviews']].astype(int)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\1856185354.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc[['Construction year','minimum nights','number of reviews']] = dfc[['Construction year','minimum nights','number of reviews']].astype(int)

In [186]:
dfc

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,Answer
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020,966,193,10,9,2021-10-19,1023.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007,142,28,30,45,2022-05-21,1023.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009,204,41,10,9,2018-11-19,1023.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013,577,115,3,74,2019-06-22,1023.0
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009,1060,212,45,49,2017-10-05,1023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102588,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,US,True,flexible,Entire home/apt,2016,618,124,1,177,2019-06-29,1023.0
102591,Columbus Ave Apt 1 block from Park,50908010324,verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,United States,US,False,strict,Entire home/apt,2005,1139,228,5,17,2019-01-04,1023.0
102593,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,US,True,strict,Private room,2017,1099,220,1,8,2015-09-06,1023.0
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016,837,167,1,1,2015-07-06,1023.0
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015,546,109,2,5,2015-10-11,1023.0

In [185]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 83868 entries, 0 to 102597
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   NAME                    83868 non-null  object
 1   host id                 83868 non-null  int64
 2   host_identity_verified  83868 non-null  object
 3   host name               83868 non-null  object
 4   neighbourhood group     83868 non-null  object
 5   neighbourhood           83868 non-null  object
 6   lat                     83868 non-null  float64
 7   long                    83868 non-null  float64
 8   country                 83868 non-null  object
 9   country code            83868 non-null  object
 10  instant_bookable        83868 non-null  object
 11  cancellation_policy     83868 non-null  object
 12  room type               83868 non-null  object
 13  Construction year       83868 non-null  int64
 14  price                   83868 non-null  int64
 15  service fee             83868 non-null  int64
 16  minimum nights          83868 non-null  int64
 17  number of reviews       83868 non-null  int64
 18  last review             83868 non-null  datetime64[ns]
 19  Answer                  83868 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(6), object(10)
memory usage: 13.4+ MB

In [184]:
dfc['last review']= pd.to_datetime(dfc['last review'])

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\2539343198.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc['last review']= pd.to_datetime(dfc['last review'])

In [188]:
dfc.drop(columns='Answer',inplace=True)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\1556519029.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc.drop(columns='Answer',inplace=True)

In [189]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 83868 entries, 0 to 102597
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   NAME                    83868 non-null  object
 1   host id                 83868 non-null  int64
 2   host_identity_verified  83868 non-null  object
 3   host name               83868 non-null  object
 4   neighbourhood group     83868 non-null  object
 5   neighbourhood           83868 non-null  object
 6   lat                     83868 non-null  float64
 7   long                    83868 non-null  float64
 8   country                 83868 non-null  object
 9   country code            83868 non-null  object
 10  instant_bookable        83868 non-null  object
 11  cancellation_policy     83868 non-null  object
 12  room type               83868 non-null  object
 13  Construction year       83868 non-null  int64
 14  price                   83868 non-null  int64
 15  service fee             83868 non-null  int64
 16  minimum nights          83868 non-null  int64
 17  number of reviews       83868 non-null  int64
 18  last review             83868 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(6), object(10)
memory usage: 12.8+ MB

In [193]:
dfc.drop(columns=['country code','country'],inplace=True)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\2965384552.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc.drop(columns=['country code','country'],inplace=True)

In [205]:
dfc

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,Strict,Private room,2020,966,193,10,9,2021-10-19
1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,Moderate,Entire home/apt,2007,142,28,30,45,2022-05-21
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,False,Moderate,Entire home/apt,2009,204,41,10,9,2018-11-19
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,True,Flexible,Entire home/apt,2013,577,115,3,74,2019-06-22
7,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,False,Moderate,Private room,2009,1060,212,45,49,2017-10-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102588,"Loft Space for Events, Meetings & Shoots",85557432222,Unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,True,Flexible,Entire home/apt,2016,618,124,1,177,2019-06-29
102591,Columbus Ave Apt 1 block from Park,50908010324,Verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,False,Strict,Entire home/apt,2005,1139,228,5,17,2019-01-04
102593,"Welcoming, Clean, Cheap on St Marks",33188605074,Verified,Felipe,Manhattan,East Village,40.72826,-73.98422,True,Strict,Private room,2017,1099,220,1,8,2015-09-06
102595,Best Location near Columbia U,77864383453,Unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,True,Moderate,Private room,2016,837,167,1,1,2015-07-06
102597,Big Studio-One Stop from Midtown,11160591270,Unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,True,Strict,Entire home/apt,2015,546,109,2,5,2015-10-11

In [198]:
dfc['host_identity_verified']= dfc['host_identity_verified'].str.title()

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\473670654.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc['host_identity_verified']= dfc['host_identity_verified'].str.title()

In [201]:
dfc['neighbourhood group'].replace('brookln','Brooklyn',inplace=True)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\3690244757.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc['neighbourhood group'].replace('brookln','Brooklyn',inplace=True)

In [204]:
dfc['cancellation_policy']= dfc['cancellation_policy'].str.title()

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\1482727358.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc['cancellation_policy']= dfc['cancellation_policy'].str.title()

In [207]:
dfc.instant_bookable = dfc.instant_bookable.astype(bool)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\3584494969.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc.instant_bookable = dfc.instant_bookable.astype(bool)

In [208]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 83868 entries, 0 to 102597
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   NAME                    83868 non-null  object
 1   host id                 83868 non-null  int64
 2   host_identity_verified  83868 non-null  object
 3   host name               83868 non-null  object
 4   neighbourhood group     83868 non-null  object
 5   neighbourhood           83868 non-null  object
 6   lat                     83868 non-null  float64
 7   long                    83868 non-null  float64
 8   instant_bookable        83868 non-null  bool
 9   cancellation_policy     83868 non-null  object
 10  room type               83868 non-null  object
 11  Construction year       83868 non-null  int64
 12  price                   83868 non-null  int64
 13  service fee             83868 non-null  int64
 14  minimum nights          83868 non-null  int64
 15  number of reviews       83868 non-null  int64
 16  last review             83868 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(2), int64(6), object(7)
memory usage: 11.0+ MB

In [210]:
dfc.NAME.rename('name',inplace=True)

0                       Clean & quiet apt home by the park
1                                    Skylit Midtown Castle
4         Entire Apt: Spacious Studio/Loft by central park
5                Large Cozy 1 BR Apartment In Midtown East
7                                          BlissArtsSpace!
                                ...
102588            Loft Space for Events, Meetings & Shoots
102591                  Columbus Ave Apt 1 block from Park
102593                 Welcoming, Clean, Cheap on St Marks
102595                       Best Location near Columbia U
102597                    Big Studio-One Stop from Midtown
Name: name, Length: 83868, dtype: object

In [212]:
dfc.host_identity_verified.rename('host identity verified',inplace=True)

0         Unconfirmed
1            Verified
4            Verified
5            Verified
7         Unconfirmed
             ...
102588    Unconfirmed
102591       Verified
102593       Verified
102595    Unconfirmed
102597    Unconfirmed
Name: host identity verified, Length: 83868, dtype: object

In [231]:
dfc.rename(columns={'host_identity_verified': 'host identity verified'},inplace=True)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\1632284260.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc.rename(columns={'host_identity_verified': 'host identity verified'},inplace=True)

In [232]:
dfc.rename(columns={'NAME': 'name'},inplace=True)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\1913760548.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc.rename(columns={'NAME': 'name'},inplace=True)

In [235]:
dfc.rename(columns={'cancellation_policy': 'cancellation policy'},inplace=True)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\1599549953.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc.rename(columns={'cancellation_policy': 'cancellation policy'},inplace=True)

In [238]:
dfc.rename(columns={'instant_bookable': 'instant bookable'},inplace=True)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\3479735812.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc.rename(columns={'instant_bookable': 'instant bookable'},inplace=True)

In [240]:
dfc.rename(columns={'Construction year': 'construction year'},inplace=True)

C:\Users\YUSEF\AppData\Local\Temp\ipykernel_24544\1623772006.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc.rename(columns={'Construction year': 'construction year'},inplace=True)

In [241]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 83868 entries, 0 to 102597
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    83868 non-null  object
 1   host id                 83868 non-null  int64
 2   host identity verified  83868 non-null  object
 3   host name               83868 non-null  object
 4   neighbourhood group     83868 non-null  object
 5   neighbourhood           83868 non-null  object
 6   lat                     83868 non-null  float64
 7   long                    83868 non-null  float64
 8   instant bookable        83868 non-null  bool
 9   cancellation policy     83868 non-null  object
 10  room type               83868 non-null  object
 11  construction year       83868 non-null  int64
 12  price                   83868 non-null  int64
 13  service fee             83868 non-null  int64
 14  minimum nights          83868 non-null  int64
 15  number of reviews       83868 non-null  int64
 16  last review             83868 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(2), int64(6), object(7)
memory usage: 13.0+ MB

In [242]:
dfc

,name,host id,host identity verified,host name,neighbourhood group,neighbourhood,lat,long,instant bookable,cancellation policy,room type,construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,Strict,Private room,2020,966,193,10,9,2021-10-19
1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,Moderate,Entire home/apt,2007,142,28,30,45,2022-05-21
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,False,Moderate,Entire home/apt,2009,204,41,10,9,2018-11-19
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,True,Flexible,Entire home/apt,2013,577,115,3,74,2019-06-22
7,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,False,Moderate,Private room,2009,1060,212,45,49,2017-10-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102588,"Loft Space for Events, Meetings & Shoots",85557432222,Unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,True,Flexible,Entire home/apt,2016,618,124,1,177,2019-06-29
102591,Columbus Ave Apt 1 block from Park,50908010324,Verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,False,Strict,Entire home/apt,2005,1139,228,5,17,2019-01-04
102593,"Welcoming, Clean, Cheap on St Marks",33188605074,Verified,Felipe,Manhattan,East Village,40.72826,-73.98422,True,Strict,Private room,2017,1099,220,1,8,2015-09-06
102595,Best Location near Columbia U,77864383453,Unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,True,Moderate,Private room,2016,837,167,1,1,2015-07-06
102597,Big Studio-One Stop from Midtown,11160591270,Unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,True,Strict,Entire home/apt,2015,546,109,2,5,2015-10-11

In [247]:
dfc.columns = dfc.columns.str.strip().str.lower().str.replace(' ', '_')

In [248]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 83868 entries, 0 to 102597
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    83868 non-null  object
 1   host_id                 83868 non-null  int64
 2   host_identity_verified  83868 non-null  object
 3   host_name               83868 non-null  object
 4   neighbourhood_group     83868 non-null  object
 5   neighbourhood           83868 non-null  object
 6   lat                     83868 non-null  float64
 7   long                    83868 non-null  float64
 8   instant_bookable        83868 non-null  bool
 9   cancellation_policy     83868 non-null  object
 10  room_type               83868 non-null  object
 11  construction_year       83868 non-null  int64
 12  price                   83868 non-null  int64
 13  service_fee             83868 non-null  int64
 14  minimum_nights          83868 non-null  int64
 15  number_of_reviews       83868 non-null  int64
 16  last_review             83868 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(2), int64(6), object(7)
memory usage: 13.0+ MB

## The Cleaning is Done 👌👌👌👌

In [249]:
dfc.to_csv('Airbnb.csv')