In [1]:
import pandas as pd 
import seaborn as sns

In [ ]:
df=pd.read_csv(r'C:\Users\YUSEF\Downloads\Compressed\Airbnb_Open_Data.csv\Airbnb_Open_Data.csv')
df

In [ ]:
df.license.value_counts()
#! drop this shit

In [ ]:
df.drop(columns='license',inplace=True)

In [ ]:
df

In [ ]:
df.host_identity_verified.unique()

In [ ]:
df.host_identity_verified.isna().value_counts()
#! 289

In [ ]:
df.host_identity_verified.isna()

In [ ]:
df.host_identity_verified

In [ ]:
df.host_identity_verified.value_counts()

In [ ]:
df

In [ ]:
dfc = df.dropna(subset=['NAME','host_identity_verified','host name','neighbourhood group','neighbourhood','lat','long','country','country code','price','Construction year','room type','cancellation_policy','instant_bookable','service fee','availability 365','calculated host listings count','review rate number','reviews per month','number of reviews','minimum nights'])

In [ ]:
dfc.dropna(subset='last review',inplace=True)

In [ ]:
dfc

In [ ]:
columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
'country code', 'instant_bookable', 'cancellation_policy', 'room type',
'Construction year', 'price', 'service fee', 'minimum nights',
'number of reviews', 'last review']
columns_to_drop = ['reviews per month',
'review rate number', 'calculated host listings count',
'availability 365', 'house_rules', 'License', 'id']

In [ ]:
dfc = dfc[columns_to_keep]
dfc

In [ ]:
dfc['neighbourhood group'].unique()

In [ ]:
# Extract meanings of cancellation policy, room type, service fee, and review differences
# Define a dictionary for cancellation policy meanings
cancellation_policy_meanings = {
    "strict": "No refund if canceled late",
    "moderate": "Partial refund if canceled",
    "flexible": "Full refund if canceled early"
}
# Define a dictionary for room type meanings
room_type_meanings = {
    "Private room": "A private room in a shared space",
    "Entire home/apt": "The entire property is rented",
    "Shared room": "A shared room in a shared space"
}
# Define the meaning of service fee
service_fee_meaning = "A fee charged for services provided"
# Calculate the difference between all reviews
dfc['Answer'] = dfc['number of reviews'].max() - dfc['number of reviews'].min()
# Combine all meanings and differences into a DataFrame

In [ ]:
dfc.price = dfc.price.str.replace(',',repl='').str.replace('$','').astype(int)

In [ ]:
dfc['service fee'] = dfc['service fee'].str.replace(',',repl='').str.replace('$','').astype(int)

In [ ]:
dfc

In [ ]:
dfc.drop(index= dfc[dfc['minimum nights'] < 0 ].index, inplace=True)

In [ ]:
dfc[dfc['minimum nights'] < 0 ]

In [ ]:
dfc

In [ ]:
# ! convert to int
dfc[['Construction year','minimum nights','number of reviews']] = dfc[['Construction year','minimum nights','number of reviews']].astype(int)

In [ ]:
dfc

In [ ]:
dfc.info()

In [ ]:
dfc['last review']= pd.to_datetime(dfc['last review'])

In [ ]:
dfc.drop(columns='Answer',inplace=True)

In [ ]:
dfc.info()

In [ ]:
dfc.drop(columns=['country code','country'],inplace=True)

In [ ]:
dfc

In [ ]:
dfc['host_identity_verified']= dfc['host_identity_verified'].str.title()

In [ ]:
dfc['neighbourhood group'].replace('brookln','Brooklyn',inplace=True)

In [ ]:
dfc['cancellation_policy']= dfc['cancellation_policy'].str.title()

In [ ]:
dfc.instant_bookable = dfc.instant_bookable.astype(bool)

In [ ]:
dfc.info()

In [ ]:
dfc.NAME.rename('name',inplace=True)

In [ ]:
dfc.host_identity_verified.rename('host identity verified',inplace=True)

In [ ]:
dfc.rename(columns={'host_identity_verified': 'host identity verified'},inplace=True)

In [ ]:
dfc.rename(columns={'NAME': 'name'},inplace=True)

In [ ]:
dfc.rename(columns={'cancellation_policy': 'cancellation policy'},inplace=True)

In [ ]:
dfc.rename(columns={'instant_bookable': 'instant bookable'},inplace=True)

In [ ]:
dfc.rename(columns={'Construction year': 'construction year'},inplace=True)

In [ ]:
dfc.info()

In [ ]:
dfc

In [ ]:
dfc.columns = dfc.columns.str.strip().str.lower().str.replace(' ', '_')

In [ ]:
dfc.info()

In [ ]:
dfc.to_csv('Airbnb.csv')

In [3]:
df2=pd.read_csv(r'C:\Users\YUSEF\Desktop\workspace for jupyter\airbnb-data-analysis\Airbnb.csv')

In [8]:
df2['minimum_total_price'] =(df2['price']*df2.minimum_nights)+df2.service_fee

In [9]:
df2

,Unnamed: 0,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,minimum_total_price
0,0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,Strict,Private room,2020,966,193,10,9,2021-10-19,9853
1,1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,Moderate,Entire home/apt,2007,142,28,30,45,2022-05-21,4288
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,False,Moderate,Entire home/apt,2009,204,41,10,9,2018-11-19,2081
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,True,Flexible,Entire home/apt,2013,577,115,3,74,2019-06-22,1846
4,7,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,False,Moderate,Private room,2009,1060,212,45,49,2017-10-05,47912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83863,102588,"Loft Space for Events, Meetings & Shoots",85557432222,Unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,True,Flexible,Entire home/apt,2016,618,124,1,177,2019-06-29,742
83864,102591,Columbus Ave Apt 1 block from Park,50908010324,Verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,False,Strict,Entire home/apt,2005,1139,228,5,17,2019-01-04,5923
83865,102593,"Welcoming, Clean, Cheap on St Marks",33188605074,Verified,Felipe,Manhattan,East Village,40.72826,-73.98422,True,Strict,Private room,2017,1099,220,1,8,2015-09-06,1319
83866,102595,Best Location near Columbia U,77864383453,Unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,True,Moderate,Private room,2016,837,167,1,1,2015-07-06,1004
83867,102597,Big Studio-One Stop from Midtown,11160591270,Unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,True,Strict,Entire home/apt,2015,546,109,2,5,2015-10-11,1201

In [11]:
df2.drop(columns='Unnamed: 0',inplace=True)

In [12]:
df2

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,minimum_total_price
0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,Strict,Private room,2020,966,193,10,9,2021-10-19,9853
1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,Moderate,Entire home/apt,2007,142,28,30,45,2022-05-21,4288
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,False,Moderate,Entire home/apt,2009,204,41,10,9,2018-11-19,2081
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,True,Flexible,Entire home/apt,2013,577,115,3,74,2019-06-22,1846
4,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,False,Moderate,Private room,2009,1060,212,45,49,2017-10-05,47912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83863,"Loft Space for Events, Meetings & Shoots",85557432222,Unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,True,Flexible,Entire home/apt,2016,618,124,1,177,2019-06-29,742
83864,Columbus Ave Apt 1 block from Park,50908010324,Verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,False,Strict,Entire home/apt,2005,1139,228,5,17,2019-01-04,5923
83865,"Welcoming, Clean, Cheap on St Marks",33188605074,Verified,Felipe,Manhattan,East Village,40.72826,-73.98422,True,Strict,Private room,2017,1099,220,1,8,2015-09-06,1319
83866,Best Location near Columbia U,77864383453,Unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,True,Moderate,Private room,2016,837,167,1,1,2015-07-06,1004
83867,Big Studio-One Stop from Midtown,11160591270,Unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,True,Strict,Entire home/apt,2015,546,109,2,5,2015-10-11,1201

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83868 entries, 0 to 83867
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    83868 non-null  object
 1   host_id                 83868 non-null  int64
 2   host_identity_verified  83868 non-null  object
 3   host_name               83868 non-null  object
 4   neighbourhood_group     83868 non-null  object
 5   neighbourhood           83868 non-null  object
 6   lat                     83868 non-null  float64
 7   long                    83868 non-null  float64
 8   instant_bookable        83868 non-null  bool
 9   cancellation_policy     83868 non-null  object
 10  room_type               83868 non-null  object
 11  construction_year       83868 non-null  int64
 12  price                   83868 non-null  int64
 13  service_fee             83868 non-null  int64
 14  minimum_nights          83868 non-null  int64
 15  number_of_reviews       83868 non-null  int64
 16  last_review             83868 non-null  object
 17  minimum_total_price     83868 non-null  int64
dtypes: bool(1), float64(2), int64(7), object(8)
memory usage: 11.0+ MB

In [16]:
df2['last_review']=pd.to_datetime(df2['last_review'])

In [17]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83868 entries, 0 to 83867
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    83868 non-null  object
 1   host_id                 83868 non-null  int64
 2   host_identity_verified  83868 non-null  object
 3   host_name               83868 non-null  object
 4   neighbourhood_group     83868 non-null  object
 5   neighbourhood           83868 non-null  object
 6   lat                     83868 non-null  float64
 7   long                    83868 non-null  float64
 8   instant_bookable        83868 non-null  bool
 9   cancellation_policy     83868 non-null  object
 10  room_type               83868 non-null  object
 11  construction_year       83868 non-null  int64
 12  price                   83868 non-null  int64
 13  service_fee             83868 non-null  int64
 14  minimum_nights          83868 non-null  int64
 15  number_of_reviews       83868 non-null  int64
 16  last_review             83868 non-null  datetime64[ns]
 17  minimum_total_price     83868 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(7), object(7)
memory usage: 11.0+ MB

In [23]:
df2

,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,minimum_total_price
0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,Strict,Private room,2020,966,193,10,9,2021-10-19,9853
1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,Moderate,Entire home/apt,2007,142,28,30,45,2022-05-21,4288
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,False,Moderate,Entire home/apt,2009,204,41,10,9,2018-11-19,2081
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,True,Flexible,Entire home/apt,2013,577,115,3,74,2019-06-22,1846
4,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,False,Moderate,Private room,2009,1060,212,45,49,2017-10-05,47912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83863,"Loft Space for Events, Meetings & Shoots",85557432222,Unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,True,Flexible,Entire home/apt,2016,618,124,1,177,2019-06-29,742
83864,Columbus Ave Apt 1 block from Park,50908010324,Verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,False,Strict,Entire home/apt,2005,1139,228,5,17,2019-01-04,5923
83865,"Welcoming, Clean, Cheap on St Marks",33188605074,Verified,Felipe,Manhattan,East Village,40.72826,-73.98422,True,Strict,Private room,2017,1099,220,1,8,2015-09-06,1319
83866,Best Location near Columbia U,77864383453,Unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,True,Moderate,Private room,2016,837,167,1,1,2015-07-06,1004
83867,Big Studio-One Stop from Midtown,11160591270,Unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,True,Strict,Entire home/apt,2015,546,109,2,5,2015-10-11,1201